name: second_brain
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ICONS
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0

  # state managements
  provider: ^6.1.2
#  get: ^4.6.6

  # BASIC
  shared_preferences: ^2.3.4
  dio: ^5.7.0
  logger: ^2.5.0
  fluttertoast: ^8.2.10
  cached_network_image: ^3.4.1
  intl: ^0.20.1
  flutter_svg: ^2.0.16

  # SYSTEMS
  device_info_plus: ^11.2.0
  package_info_plus: ^8.1.2
  connectivity_plus: ^6.1.1

  # ANIMATION/ LOADER
  flutter_spinkit: ^5.2.1
  animate_do: ^3.3.4

  # FIREBASE
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4


  # IMAGE AND FILE PICKER
  image_picker: ^1.1.2
  file_picker: ^8.1.7
  excel: ^4.0.6
  path_provider: ^2.1.5
  file_selector: ^1.0.3
  crop_image: ^1.0.15

  youtube_explode_dart: ^2.3.6
  just_audio: ^0.9.42
  just_audio_background: ^0.0.1-beta.14
  video_player: ^2.9.2
  open_filex: ^4.6.0
  palette_generator: ^0.3.3+5
  go_router: ^14.6.3




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true




#  Platform  Firebase App Id
#  web       1:191114173571:web:bdb0d0c17009d972760fb6
#  android   1:191114173571:android:53e287acda30a44d760fb6
#  ios       1:191114173571:ios:241d30c47176f812760fb6
#  macos     1:191114173571:ios:3f08397cacc5055b760fb6
