// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-UscHgA9jEvkbB7ar-Tg_ebUe7NQwgCA',
    appId: '1:191114173571:web:bdb0d0c17009d972760fb6',
    messagingSenderId: '191114173571',
    projectId: 'second-brain-3cfd4',
    authDomain: 'second-brain-3cfd4.firebaseapp.com',
    storageBucket: 'second-brain-3cfd4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWjXhaYaZz9HBBt_W02FvxKKOxazYbX-g',
    appId: '1:191114173571:android:53e287acda30a44d760fb6',
    messagingSenderId: '191114173571',
    projectId: 'second-brain-3cfd4',
    storageBucket: 'second-brain-3cfd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxoaXsM20RmsLgJ19szW5NwLZwZ6oV2G4',
    appId: '1:191114173571:ios:241d30c47176f812760fb6',
    messagingSenderId: '191114173571',
    projectId: 'second-brain-3cfd4',
    storageBucket: 'second-brain-3cfd4.appspot.com',
    iosBundleId: 'com.example.secondBrain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxoaXsM20RmsLgJ19szW5NwLZwZ6oV2G4',
    appId: '1:191114173571:ios:3f08397cacc5055b760fb6',
    messagingSenderId: '191114173571',
    projectId: 'second-brain-3cfd4',
    storageBucket: 'second-brain-3cfd4.appspot.com',
    iosBundleId: 'com.example.secondBrain.RunnerTests',
  );
}
